### ISSUE TITLE
Not work in Gnome 46

### ISSUE THREAD

**Issue by jalediazb** [MajortomVR/simple-timer-extension#14]

**Comment by nahiyan** [comment]
You can easily patch this. Go to the source directory and edit the "extension.js" file. Replace all occurrences of `.add(` with `.add_child(`.

Afterwards, you can edit the "metadata.json" and increment the "shell-version" from 45 to 46 (otherwise GNOME 46 wouldn't load it). As a convention, you can bump the "version" as well.

P.S. You need to reload the GNOME shell, which you can easily do by pressing Alt + F2 and running the "r" command. Or you can simply sign out and sign back in.

**Comment by fatrattombala** [comment]
> You can easily patch this. Go to the source directory (the path is likely `~/.local/share/gnome-shell/extensions/simple-timer@majortomvr.github.com`) and edit the `extension.js` file. Replace all occurrences of `.add(` with `.add_child(`.
> 
> Afterwards, you need to edit the `metadata.json` and increment the `shell-version` from 45 to 46 (otherwise GNOME 46 wouldn't load it). As a convention, you should bump the `version` as well.
> 
> P.S. For the changes to take effect, you need to reload the GNOME shell. You can conveniently do so by pressing Alt + F2 and running the `r` command. Or you can simply sign out and sign back in.

works perfectly, thank you!
